[project]
name = "research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "camel-converter>=5.1.0",
    "dataframe-image>=0.2.7",
    "fastparquet>=2026.5.0",
    "kaleido>=1.3.0",
    "numba>=0.67.0",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "plotly>=6.8.0",
    "psutil>=7.2.2",
    "sci-learn>=0.1.4",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "tabulate>=0.10.0",
]

[dependency-groups]
dev = [
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.6.2",
    "notebook>=7.6.0",
    "ruff>=0.16.0",
]
